name: CI

on:
  pull_request:
    branches:   
      - main
      - develop
      
jobs:
  ci-test-checklist:
    name: normal CI checks
    runs-on: test_mac_runner

    steps: 
      - name: checkout
        uses: actions/checkout@v4
      
      - name: happy flow
        run: ./brew_installer.sh -e
        
 
